baseURL = 'https://sw1tch9789.github.io/ColorfuLS/'
title = 'ColorfuLS'
languageCode = 'ja'
defaultContentLanguage = 'ja'
defaultContentLanguageInSubdir = false

enableGitInfo = true

[params]
description = "ColorfuLS documentation"

[params.ui]
sidebar_menu_compact = false
ul_show = 1

[[menu.main]]
name = "Documentation"
url = "/docs/"
weight = 10

[[menu.main]]
name = "Tutorial"
url = "/docs/tutorial/"
weight = 20

[[menu.main]]
name = "Examples"
url = "/docs/examples/"
weight = 30

[languages.ja]
languageName = "Japanese"
weight = 1
